### ISSUE TITLE
Metallb webhook-service renamed to metallb-webhook-service

### ISSUE THREAD

**Issue by black-dragon74** [techno-tim/k3s-ansible#487]
While deploying the manifests for **MetalLB version v0.14.4**, the `wehbhook-service` is named `metallb-webhook-service`.

This causes the post task to fail with an error.

Posting it here for anyone else facing the same. I can send a PR for the same. 

It would make sense to dynamically set a var for service name depending of the config values: `metal_lb_*_tag_version`.

WDYT @timothystewart6 ?

Regards

**Comment by tfs** [comment]
> Hey! I am confused on how this is happening? Is this in an upgrade scenario? Or using an old tag with the latest playbook?

Happened to me, too. Scenario for me: changed the version for metallb in the all.yml in my inventory.

**Comment by black-dragon74** [comment]
> Hey! I am confused on how this is happening? Is this in an upgrade scenario? Or using an old tag with the latest playbook?

They changed the webhook service name starting with v0.14.4 (added metallb prefix) to more accurately denote where the service comes from.

**Comment by timothystewart6** [comment]
Got it.  Hmmm.... Not sure I want to make any changes since this is a point in time, otherwise we would have to account for every breaking change with every included dependency.  We always ensure that the current configuration works on clean machines (since we run it in CI).  Generally speaking (although it does work) upgrading using the playbook is kind of an edge case since we recommend using helm or gitops to handle this after the cluster is bootstrapped.

**Comment by konstantin-kornienko** [comment]
Trying to fix this issue, faced it too.
https://github.com/techno-tim/k3s-ansible/pull/528/files
